# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install libssl-dev curl pkg-config
    curl -LSsf https://sh.rustup.rs | sh -s - -y -v
    source ~/.cargo/env
    cargo build --release --features vendored-openssl
  displayName: 'Build cargo'
- script: |
    git clone --depth=1 https://github.com/pgdurand/github-release-api.git api
    ./api/github_release_manager.sh -l msizanoen1 -t $(GITHUB_TOKEN) -o msizanoen1 -r ghc-comp -d cargo4 -c create || true
    cp target/release/cargo cargo.bin
    ./api/github_release_manager.sh -l msizanoen1 -t $(GITHUB_TOKEN) -o msizanoen1 -r ghc-comp -d cargo4 -c upload cargo.bin
  displayName: 'Upload artifacts'
- publish: target/release/cargo
