# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    apt-get install libssl-dev curl
    curl -LSsf https://sh.rustup.rs | sh -s - -- -y -v
    source ~/.cargo/env
    cargo build --release
  displayName: 'Build cargo'
- publish: target/release/cargo
